name: "EPAC Dev Pipeline"

on:
  push:
    branches:
      - feature/*
    paths:
      - Definitions/**
      - Pipelines/**
  pull_request:
    branches:
      - feature/*

jobs:
  plan:
    name: "Plan ${{ github.ref_name }}"
    runs-on: ubuntu-latest
    steps:
      - name: Run Plan Template
        uses: actions/checkout@v3
      - name: Execute Plan
        run: |
          echo "Running plan with service connection: sc-epac-plan"

  deploy:
    name: "Deploy ${{ github.ref_name }}"
    runs-on: ubuntu-latest
    needs: plan
    if: ${{ success() }}
    steps:
      - name: Run Deploy Template
        uses: actions/checkout@v3
      - name: Execute Deploy
        run: |
          echo "Deploying with service connection: sc-epac-dev"